import type { Role } from "@homelabconnect/shared";

export interface UserSeed {
  email: string;
  password: string;
  role: Role;
  firstName: string;
  lastName: string;
  middleName: string | null;
  phone: string | null;
  avatar: string | null;
  isActive: boolean;
  emailVerified: boolean;
}

export const SEED_USERS: UserSeed[] = [
  {
    email: "patient01@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Santos",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient02@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Reyes",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient03@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Cruz",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient04@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Garcia",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient05@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Mendoza",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient06@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Torres",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient07@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Flores",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient08@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Gonzales",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient09@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Ramos",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient10@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Aquino",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient11@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Navarro",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient12@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Castro",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient13@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "DelosReyes",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient14@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Bautista",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient15@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Villanueva",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient16@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Salazar",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient17@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Pascual",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient18@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Domingo",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient19@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Mercado",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "patient20@homelabconnect.local",
    password: "patient123",
    role: "patient",
    firstName: "Patient",
    lastName: "Manalo",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },

  // staff
  {
    email: "admin@homelabconnect.local",
    password: "admin123",
    role: "admin",
    firstName: "Admin",
    lastName: "User",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "medteam@homelabconnect.local",
    password: "medteam123",
    role: "med_team",
    firstName: "Medic",
    lastName: "Team",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "medteam2@homelabconnect.local",
    password: "medteam123",
    role: "med_team",
    firstName: "Medic",
    lastName: "Two",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "medteam3@homelabconnect.local",
    password: "medteam123",
    role: "med_team",
    firstName: "Medic",
    lastName: "Three",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "medteam4@homelabconnect.local",
    password: "medteam123",
    role: "med_team",
    firstName: "Medic",
    lastName: "Four",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "medteam5@homelabconnect.local",
    password: "medteam123",
    role: "med_team",
    firstName: "Medic",
    lastName: "Five",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "doctor@homelabconnect.local",
    password: "doctor123",
    role: "doctor",
    firstName: "Doctor",
    lastName: "User",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
  {
    email: "support@homelabconnect.local",
    password: "support123",
    role: "support",
    firstName: "Support",
    lastName: "Agent",
    middleName: null,
    phone: null,
    avatar: null,
    isActive: true,
    emailVerified: true,
  },
];
